### PR TITLE
fix: estimate gas bug

### LINKED ISSUE #185: [BUG] Enabling KYB stops KYC users from claiming
https://github.com/mento-protocol/airgrab-interface/pull/184

### PR DESCRIPTION
**Pull request by baroooo**
## Description

Fixes the bug that blocks KYCed users from claiming.
Exact issue could not be identified, so it reverts the recent changes to the problematic function.

## Tested
Tested locally with testing accounts, both KYC and KYB claims reverts with contract errors so should work on prod.

## Related issue

fixes  #185

### CODE REVIEW

File: src/hooks/use-estimate-gas.ts [hunk 1]
```diff
@@ -15,20 +15,20 @@ export const useEstimateGas = (tx: EstimateContractGasParameters | null) => {
...
-        if (!publicClient) throw new Error("No public client available");
-        const gas = await publicClient.estimateContractGas(tx);
-        return gas;
+        if (!tx) return;
+        if (!publicClient) return;
+        const gasEstimate = await publicClient.estimateContractGas(tx);
+        setGasPrice(gasEstimate);
       } catch (error) {
-        // log error then rethrow it to be caught by SWR
-        Sentry.captureException(error);
```
Comment (bayological) [inline src/hooks/use-estimate-gas.ts:28]: Is it still worth logging to Sentry? Do we expect the message from the error message to be enough context?

**Review by bayological — APPROVED** [review]

File: src/hooks/use-estimate-gas.ts (hunk 1 above)
Comment (baroooo) [reply src/hooks/use-estimate-gas.ts:28]: the error that is caught here would most probably be related to a contract revert (eg, the user already claimed, not eligible or proof expired)
I think it would be better for the user to see it, rather then us. users had no feedback before about what was going wrong. we can potentially log to sentry as well but not sure if that adds too much benefit considering users sends the screen shot when they open a ticket and we would log things that are user specific errors and not an issue in general.
let me know if you disagree, we can still add it

**Review by denviljclarke — APPROVED** [review]
LG 🫡
