### PR TITLE
Fix: Estimate gas for claim refactor

### LINKED ISSUE #172: [BUG]: Cannot claim with celo terminal
Either implement a fix or come up with a sufficient workaround that enables celo terminal users to claim. This should work for users who also use hardware wallets.

### PR DESCRIPTION
**Pull request by denviljclarke**
This PR refactors the gas estimation changes made in #176. It cleans up the gas estimation logic, moving it into a dedicated hook.

fixes #172

### CODE REVIEW

File: src/hooks/use-claim-mento.tsx [hunk 1]
```diff
@@ -37,6 +39,26 @@ export const useClaimMento = ({
...
+  const gasEstimate = useEstimateGas(
+    preparedClaimArgs
+      ? {
+          address: addresses.Airgrab as Address,
+          abi: Airdrop,
+          functionName: "claim",
+          args: preparedClaimArgs,
+          account: address as Address,
+        }
+      : null,
```
Comment (RyRy79261) [inline src/hooks/use-claim-mento.tsx:60]: You could use the `query` part of this hook to `enable` the query

This hook I think auto updates while there's something present so in theory, the intended pattern is to provide an params and select whether it runs

**Review by RyRy79261 — APPROVED** [review]

**Review by philbow61 — APPROVED** [review]
